= Rust: Launchpad

Rust tutorials from https://www.shuttle.rs/launchpad.

* Issue #2: Structs and Enums - A podcast app
* Issue #3: Ownership and Error Handling - A Sudoku solver
* Issue #4: Ownership and Lifetimes - A lottery number generator
* Issue #5: Traits - An image processing app
** Follow up
*** Try figuring out a few other image operations and create new handlers.
*** Look at the `imageproc` crate and see if you can do some advanced operations.
*** Send a few images in parallel and see what happens.
*** https://www.youtube.com/watch?v=WgVWxLuPvfQ[Video: A talk about traits]
* Issue #6: CRUD - A CRUD API
** Follow up
*** Change the type of `published_date` to `chrono::NaiveDate` and see what happens.
*** Try working with other data types than `Strings`
*** Can you add the ID to the struct as well? How do you make sure that the user should not send one when you create a new article
*** Can you limit access to creating articles?
*** Implement the "update" and "delete" function yourself!

== Contributing

The best way to get started is to build and run a local dev container.

You can use https://podman.io[Podman] or any other OCI compliant container manager.
The dev container has all the required dependencies for working with the project.

[source, bash]
----
container/build.sh
container/run.sh
----

From inside the container, you can then run some workflows.

[source, bash]
----
cargo test    # run tests
cargo clippy  # run linters
cargo run
----

== License

Copyright (C) 2023 Andreas Longo

GNU General Public License v3.0 or later
