= Rust: Launchpad

Rust tutorials from https://www.shuttle.rs/launchpad.

* Issue #2: Structs and Enums - A podcast app
* Issue #3: Ownership and Error Handling - A Sudoku solver
* Issue #4: Ownership and Lifetimes - A lottery number generator

* Issue #5: Traits - An image processing app
** Follow up
*** Try figuring out a few other image operations and create new handlers.
*** Look at the `imageproc` crate and see if you can do some advanced operations.
*** Send a few images in parallel and see what happens.
*** https://www.youtube.com/watch?v=WgVWxLuPvfQ[Video: A talk about traits]

* Issue #6: Databases - A CRUD API
** Follow up
*** Change the type of `published_date` to `chrono::NaiveDate` and see what happens.
*** Try working with other data types than `Strings`
*** Can you add the ID to the struct as well? How do you make sure that the user should not send one when you create a new article
*** Can you limit access to creating articles?
*** Implement the "update" and "delete" function yourself!

* Issue #7: Defining traits - A CRUD API v2
** Follow up
*** Fix bug
*** Trying to abstract the SQL statement away as well. What if you get an actual article when calling `Article::select(key)`? How would you implement that? What would be a good abstraction?
*** And if you go that route, what about async methods in Rust? They are not so easily implemented at the time of this writing, but there are some crates that help you with that. Can you find it? How does it work?

* Issue #8: The Default trait, working with Arc and RwLock, and using serde - A web sockets chat
** Follow up
*** Try figuring out how to wire them up in your Axum applications. A few leads:
**** Maybe create new named routes and return the content as String.
**** Try figuring out how to serve static files using tower_http::services::ServeDir and shuttle_static_folder

* Issue #9: Trait bounds - Server side validation
** Follow up
*** TODOs in main.rs
*** From here on you can do a lot more. Now that you have a validated JSON input, you can use it to create a user in a database, write the activation route, and so many more things.
*** https://docs.rs/async-trait/latest/async_trait/index.html

* Issue #10: More on traits - Serving HTML
** Follow up
*** Use Askama features instead of Newtype pattern
+
----
$ cargo add askama --features with-axum
$ cargo add askama_axum
----

== Contributing

The best way to get started is to build and run a local dev container.

You can use https://podman.io[Podman] or any other OCI compliant container manager.
The dev container has all the required dependencies for working with the project.

[source, bash]
----
container/build.sh
container/run.sh
----

From inside the container, you can then run some workflows.

[source, bash]
----
cargo test    # run tests
cargo clippy  # run linters
cargo run
----

== License

Copyright (C) 2023 Andreas Longo

GNU General Public License v3.0 or later
