[package]
name = "mksshkey"
version = "0.1.0"
edition = "2021"
authors = ["Andreas Longo"]
license = "GPL-3.0-or-later"
repository = "https://github.com/andreaslongo/mksshkey"

[dependencies]
anstream = "0.6.4"
clap = { version = "4.4.6", features = ["derive"] }
owo-colors = "3.5.0"
